ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: ./mvnw install
  command: mv banco.sqlite ./target/bin/ && ./target/bin/webapp
vscode:
  extensions:
    - alexcvzz.vscode-sqlite@0.12.0:1159ee1f58892d78a121071408429b7a