version: '3'
services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: biblioteca
        volumes:
            - ./db/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"